[package]
name = "hybrid-renderer"
version = "0.1.0"
edition = "2024"

[features]
default = ["shader-hot-reload"]
shader-hot-reload = ["dep:notify"]

[dependencies]
winit = "0.29"
wgpu = "0.20"
pollster = "0.3"
env_logger = "0.11"
log = "0.4"
bytemuck = { version = "1.16", features = ["derive"] }
image = "0.25.9"
glam = { version = "0.32.0", features = ["bytemuck", "mint"] }
notify = { version = "8.2.0", optional = true }
anyhow = "1.0.102"
gltf = "1.4.1"

[lib]
name = "hybrid_renderer"
path = "src/lib.rs"
crate-type = ["rlib"]
